/**
 * French lesson registry — A1 foundations organized into pronunciation, vocabulary, and conversations.
 */

import type { ContentItem, Lesson, Unit } from "../../../core/lesson-types.ts";
import { generateExercises, type ContentSet } from "../../../core/exercise-generator.ts";
import { frenchA1ByTerms, frenchA1Vocab } from "../data/a1-vocab.ts";
import { cloze, introItems, mc, vocabSRS } from "./helpers.ts";

function content(items: ContentItem[]): ContentSet {
  return { items, productionLabel: "French" };
}

function vocabularyLesson(
  id: string,
  title: string,
  prerequisites: string[],
  items: ContentItem[],
  introduction: string,
  skill: string,
): Lesson {
  const exerciseItems = items.slice(0, 8);
  const lessonContent = content(exerciseItems);

  return {
    id,
    unit: "vocabulary",
    unitIndex: 2,
    title,
    prerequisites,
    introduction: {
      text: introduction,
      items: introItems(exerciseItems),
    },
    exercises: [
      ...generateExercises(lessonContent, "recognition"),
      ...generateExercises(lessonContent, "production").slice(0, 3),
      ...generateExercises({ items: exerciseItems.slice(0, 5) }, "matching"),
    ],
    srsItems: vocabSRS(items, `french_a1_${skill}`),
    skillsTaught: [`french_a1_${skill}`],
    furiganaLevel: "full",
  };
}

const greetingItems = frenchA1ByTerms([
  "bonjour",
  "salut",
  "bonsoir",
  "au revoir",
  "merci",
  "s'il vous plaît",
  "s'il te plaît",
  "pardon",
  "désolé",
  "oui",
  "non",
  "peut-être",
  "d'accord",
  "monsieur",
  "madame",
  "mademoiselle",
]);

const peopleNumberItems = frenchA1ByTerms([
  "je",
  "tu",
  "vous",
  "il",
  "elle",
  "nous",
  "ils",
  "elles",
  "moi",
  "toi",
  "un",
  "une",
  "deux",
  "trois",
  "quatre",
  "cinq",
  "six",
  "sept",
  "huit",
  "neuf",
  "dix",
  "zéro",
]);

const timePlaceItems = frenchA1ByTerms([
  "aujourd'hui",
  "demain",
  "hier",
  "matin",
  "après-midi",
  "soir",
  "nuit",
  "jour",
  "semaine",
  "mois",
  "année",
  "heure",
  "minute",
  "maison",
  "école",
  "travail",
  "gare",
  "restaurant",
  "café",
  "hôtel",
  "magasin",
  "supermarché",
  "rue",
  "ville",
  "pays",
  "France",
  "Paris",
]);

const foodPeopleItems = frenchA1ByTerms([
  "eau",
  "un café",
  "thé",
  "pain",
  "fromage",
  "fruit",
  "pomme",
  "légume",
  "viande",
  "poisson",
  "riz",
  "lait",
  "vin",
  "bière",
  "addition",
  "homme",
  "femme",
  "enfant",
  "ami",
  "amie",
  "famille",
  "mère",
  "père",
  "frère",
  "sœur",
  "professeur",
  "étudiant",
  "étudiante",
  "docteur",
]);

const verbItems = frenchA1ByTerms([
  "avoir",
  "être",
  "aller",
  "venir",
  "faire",
  "parler",
  "comprendre",
  "manger",
  "boire",
  "acheter",
  "aimer",
  "vouloir",
  "pouvoir",
  "savoir",
  "regarder",
  "écouter",
  "lire",
  "écrire",
]);

const descriptionQuestionItems = frenchA1ByTerms([
  "grand",
  "petit",
  "bon",
  "bonne",
  "mauvais",
  "nouveau",
  "chaud",
  "froid",
  "facile",
  "difficile",
  "cher",
  "gratuit",
  "ici",
  "là-bas",
  "où",
  "quand",
  "comment",
  "combien",
  "qui",
  "quoi",
  "pourquoi",
]);

export const frenchLessons: Lesson[] = [
  {
    id: "1.1",
    unit: "pronunciation",
    unitIndex: 1,
    title: "French Sounds and Silent Letters",
    prerequisites: [],
    introduction: {
      text: "French spelling often keeps final consonants silent. In A1 words, final -s, -t, -d, and -x are usually not pronounced unless a liaison connects them to the next word.",
      items: [
        { word: "salut", reading: "sah-loo", meaning: "final -t is silent" },
        { word: "vous", reading: "voo", meaning: "final -s is silent alone" },
        { word: "grand", reading: "grahn", meaning: "final -d is silent" },
        { word: "deux", reading: "duh", meaning: "final -x is silent alone" },
      ],
    },
    exercises: [
      mc("In **salut**, which final letter is normally silent?", "t", ["s", "a", "u"]),
      mc("In **vous**, which final letter is normally silent?", "s", ["v", "o", "u"]),
      mc("In **grand**, which final letter is normally silent?", "d", ["g", "r", "n"]),
      mc("In **deux**, which final letter is normally silent?", "x", ["d", "e", "u"]),
      cloze("Type the silent final letter in **petit**.", "t", "Final -t is usually silent."),
      cloze("Type the silent final letter in **froid**.", "d", "Final -d is usually silent."),
      mc("Which word has a silent final -s when said alone?", "vous", ["merci", "bonjour", "madame"]),
      mc("Which word has a silent final -x when said alone?", "deux", ["trois", "sept", "cinq"]),
      mc("What is the safest A1 rule for many final consonants?", "do not pronounce them unless linked", ["always pronounce them strongly", "replace them with r", "turn them into h"]),
      cloze("Type the missing word: final consonants are often ____ in French.", "silent", undefined, undefined, ["not pronounced"]),
    ],
    srsItems: [],
    skillsTaught: ["silent_letters"],
    furiganaLevel: "full",
  },
  {
    id: "1.2",
    unit: "pronunciation",
    unitIndex: 1,
    title: "Liaison Basics",
    prerequisites: ["1.1"],
    introduction: {
      text: "Liaison links a normally silent final consonant to a following vowel sound. In beginner French, common examples are vous avez, les amis, and un ami.",
      items: [
        { word: "vous avez", reading: "voo-zah-vay", meaning: "you have; s links as z" },
        { word: "les amis", reading: "lay-zah-mee", meaning: "the friends; s links as z" },
        { word: "un ami", reading: "uh-nah-mee", meaning: "a male friend; n links" },
        { word: "deux enfants", reading: "duh-zahn-fahn", meaning: "two children; x links as z" },
      ],
    },
    exercises: [
      mc("In **vous avez**, the liaison sound is:", "z", ["s", "t", "r"]),
      mc("In **les amis**, the final -s sounds like:", "z", ["sh", "k", "m"]),
      mc("In **un ami**, the liaison links with:", "n", ["t", "z", "p"]),
      mc("In **deux enfants**, final -x links like:", "z", ["x", "s", "d"]),
      cloze("Type the liaison sound in **vous avez**.", "z", "The silent -s wakes up as z."),
      cloze("Type the liaison sound in **les amis**.", "z", "The silent -s wakes up as z."),
      mc("When does liaison happen?", "before a following vowel sound", ["after every comma", "only before consonants", "only in written French"]),
      mc("Which phrase usually has liaison?", "vous avez", ["vous parlez", "bon soir", "merci beaucoup"]),
      mc("Which phrase usually has liaison?", "les amis", ["les livres", "les tables", "les professeurs"]),
      cloze("Complete the idea: liaison links a silent final consonant before a ____ sound.", "vowel", undefined, undefined, ["vowel sound"]),
    ],
    srsItems: [],
    skillsTaught: ["liaison"],
    furiganaLevel: "full",
  },
  {
    id: "1.3",
    unit: "pronunciation",
    unitIndex: 1,
    title: "Nasal Vowels",
    prerequisites: ["1.2"],
    introduction: {
      text: "French has nasal vowels where n or m marks the vowel quality instead of being fully pronounced. A1 examples include bon, pain, vin, enfant, and maison.",
      items: [
        { word: "bon", reading: "bohn", meaning: "nasal on" },
        { word: "pain", reading: "pan", meaning: "nasal in" },
        { word: "vin", reading: "van", meaning: "nasal in" },
        { word: "enfant", reading: "ahn-fahn", meaning: "nasal en/an twice" },
      ],
    },
    exercises: [
      mc("Which word has a nasal vowel?", "bon", ["merci", "salut", "madame"]),
      mc("Which food word has a nasal vowel?", "pain", ["pomme", "lait", "bière"]),
      mc("Which drink word has a nasal vowel?", "vin", ["eau", "thé", "un café"]),
      mc("Which word has two nasal vowel sounds?", "enfant", ["famille", "professeur", "école"]),
      cloze("Type the French word for **bread**.", "pain", "It has a nasal vowel.", undefined, ["pan"]),
      cloze("Type the French word for **wine**.", "vin", "It has a nasal vowel.", undefined, ["van"]),
      mc("In beginner pronunciation hints, **maison** is close to:", "meh-zohn", ["mah-ee-son", "may-sonn", "mee-zan"]),
      mc("In beginner pronunciation hints, **France** is close to:", "frahns", ["fran-kay", "frass", "frah-nee"]),
      mc("Which pair both has nasal vowels?", "pain and vin", ["merci and salut", "pomme and lait", "rue and ville"]),
      cloze("Nasal vowels are often marked by n or ____ after the vowel.", "m"),
    ],
    srsItems: [],
    skillsTaught: ["nasal_vowels"],
    furiganaLevel: "full",
  },
  vocabularyLesson(
    "2.1",
    "Greetings and Politeness",
    ["1.3"],
    greetingItems,
    "Start A1 French with greetings, polite words, and basic social signals.",
    "greetings",
  ),
  vocabularyLesson(
    "2.2",
    "People, Pronouns, and Numbers",
    ["2.1"],
    peopleNumberItems,
    "Pronouns and numbers let you introduce people, count, and answer basic personal questions.",
    "people_numbers",
  ),
  vocabularyLesson(
    "2.3",
    "Time and Places",
    ["2.2"],
    timePlaceItems,
    "Time and place words support plans, locations, and simple travel situations.",
    "time_places",
  ),
  vocabularyLesson(
    "2.4",
    "Food, Drink, and People",
    ["2.3"],
    foodPeopleItems,
    "Food, drink, family, and common people words cover everyday A1 conversations.",
    "food_people",
  ),
  vocabularyLesson(
    "2.5",
    "Everyday Verbs",
    ["2.4"],
    verbItems,
    "These infinitive verbs are the base forms students need for wants, needs, movement, and daily activities.",
    "verbs",
  ),
  vocabularyLesson(
    "2.6",
    "Descriptions and Questions",
    ["2.5"],
    descriptionQuestionItems,
    "Adjectives and question words turn isolated vocabulary into useful beginner exchanges.",
    "descriptions_questions",
  ),
  {
    id: "3.1",
    unit: "conversations",
    unitIndex: 3,
    title: "Introducing Yourself",
    prerequisites: ["2.6"],
    introduction: {
      text: "A1 introductions use fixed patterns: Je m'appelle..., Je suis..., J'habite..., and Je parle.... Keep answers short and clear.",
      items: [
        { word: "Je m'appelle Ana.", reading: "zhuh mah-pel Ana", meaning: "My name is Ana." },
        { word: "Je suis étudiant.", reading: "zhuh swee ay-too-dyahn", meaning: "I am a student." },
        { word: "J'habite à Paris.", reading: "zhah-beet ah pah-ree", meaning: "I live in Paris." },
        { word: "Je parle français.", reading: "zhuh parl frahn-seh", meaning: "I speak French." },
      ],
    },
    exercises: [
      mc("Which sentence means **My name is Ana**?", "Je m'appelle Ana.", ["Je suis Ana.", "J'habite Ana.", "Je parle Ana."]),
      mc("Which sentence means **I am a student**?", "Je suis étudiant.", ["Je vais étudiant.", "Je mange étudiant.", "Je parle étudiant."]),
      cloze("Complete: Je m'____ Ana.", "appelle", "Use the name pattern."),
      cloze("Complete: Je ____ étudiant.", "suis", "Use être: je suis."),
      cloze("Complete: J'____ à Paris.", "habite", "Use the living-place pattern."),
      mc("Which question asks for a name?", "Comment vous appelez-vous ?", ["Où habitez-vous ?", "Combien ça coûte ?", "Quand partez-vous ?"]),
      mc("Which answer fits **Où habitez-vous ?**", "J'habite à Paris.", ["Je m'appelle Ana.", "Merci beaucoup.", "Je voudrais de l'eau."]),
      cloze("Type the French pronoun for **I**.", "je"),
      mc("In a formal first meeting, use:", "vous", ["tu", "toi", "moi"]),
      cloze("Complete: Je ____ français.", "parle", "Say what language you speak."),
    ],
    srsItems: [],
    skillsTaught: ["introductions"],
    furiganaLevel: "partial",
  },
  {
    id: "3.2",
    unit: "conversations",
    unitIndex: 3,
    title: "Ordering at a Cafe",
    prerequisites: ["3.1"],
    introduction: {
      text: "Cafe exchanges often combine Je voudrais..., s'il vous plaît, merci, and l'addition. Use polite vous forms with staff.",
      items: [
        { word: "Je voudrais un café.", reading: "zhuh voo-dreh uhn kah-fay", meaning: "I would like a coffee." },
        { word: "Un verre d'eau, s'il vous plaît.", reading: "uhn vehr doh seel voo pleh", meaning: "A glass of water, please." },
        { word: "L'addition, s'il vous plaît.", reading: "lah-dee-syohn seel voo pleh", meaning: "The bill, please." },
        { word: "Merci beaucoup.", reading: "mehr-see boh-koo", meaning: "Thank you very much." },
      ],
    },
    exercises: [
      mc("Which phrase politely orders coffee?", "Je voudrais un café.", ["Je suis un café.", "Je parle un café.", "Je vais un café."]),
      mc("Which phrase asks for the bill?", "L'addition, s'il vous plaît.", ["La gare, s'il vous plaît.", "La maison, s'il vous plaît.", "La semaine, s'il vous plaît."]),
      cloze("Complete: Je ____ un café.", "voudrais", "Use the polite ordering pattern."),
      cloze("Complete: L'____, s'il vous plaît.", "addition", "Ask for the bill."),
      mc("With restaurant staff, the safer A1 pronoun is:", "vous", ["tu", "toi", "ils"]),
      mc("Which word means water?", "eau", ["pain", "riz", "lait"]),
      cloze("Type the French word for **please formal**.", "s'il vous plaît", undefined, undefined, ["s'il vous plait", "sil vous plait"]),
      mc("Which answer best follows receiving your drink?", "merci", ["non", "pourquoi", "hier"]),
      cloze("Type the French word for **bread**.", "pain"),
      mc("Which word means **coffee** in this lesson?", "un café", ["thé", "eau", "vin"]),
    ],
    srsItems: [],
    skillsTaught: ["cafe_ordering"],
    furiganaLevel: "partial",
  },
  {
    id: "3.3",
    unit: "conversations",
    unitIndex: 3,
    title: "Asking for Directions and Prices",
    prerequisites: ["3.2"],
    introduction: {
      text: "A1 travel exchanges rely on où, combien, c'est, and place words. Use excusez-moi before asking a stranger for help.",
      items: [
        { word: "Où est la gare ?", reading: "oo eh lah gahr", meaning: "Where is the train station?" },
        { word: "C'est ici.", reading: "seh tee-see", meaning: "It is here." },
        { word: "C'est là-bas.", reading: "seh lah-bah", meaning: "It is over there." },
        { word: "Combien ça coûte ?", reading: "kohm-byen sah koot", meaning: "How much does it cost?" },
      ],
    },
    exercises: [
      mc("Which question asks **Where is the train station?**", "Où est la gare ?", ["Quand est la gare ?", "Qui est la gare ?", "Pourquoi est la gare ?"]),
      mc("Which phrase means **It is here**?", "C'est ici.", ["C'est là-bas.", "C'est demain.", "C'est cher."]),
      mc("Which phrase asks a price?", "Combien ça coûte ?", ["Comment tu vas ?", "Où est Paris ?", "Qui est-ce ?"]),
      cloze("Complete: ____ est la gare ?", "Où", "Ask where.", undefined, ["ou"]),
      cloze("Complete: C'est ____.", "ici", "Say it is here."),
      cloze("Complete: Combien ça ____ ?", "coûte", "Ask price.", undefined, ["coute"]),
      mc("Which word means **street**?", "rue", ["ville", "pays", "hôtel"]),
      mc("Which word means **over there**?", "là-bas", ["ici", "aujourd'hui", "demain"]),
      mc("Which adjective can describe a high price?", "cher", ["gratuit", "facile", "froid"]),
      cloze("Type the French question word for **how much/how many**.", "combien"),
    ],
    srsItems: [],
    skillsTaught: ["directions_prices"],
    furiganaLevel: "partial",
  },
];

export const frenchUnits: Unit[] = [
  {
    index: 1,
    id: "pronunciation",
    name: "Pronunciation",
    icon: "🔊",
    lessonIds: frenchLessons.filter((lesson) => lesson.unit === "pronunciation").map((lesson) => lesson.id),
  },
  {
    index: 2,
    id: "vocabulary",
    name: "A1 Vocabulary",
    icon: "📘",
    lessonIds: frenchLessons.filter((lesson) => lesson.unit === "vocabulary").map((lesson) => lesson.id),
  },
  {
    index: 3,
    id: "conversations",
    name: "First Conversations",
    icon: "💬",
    lessonIds: frenchLessons.filter((lesson) => lesson.unit === "conversations").map((lesson) => lesson.id),
  },
];

export const frenchA1VocabularyItems = frenchA1Vocab;
