/**
 * Example sentence bank for common Spanish A1 vocabulary.
 */

export const spanishExampleSentences: Record<string, string[]> = {
  hola: ["¡Hola! ¿Cómo estás?", "Hola, me llamo Ana."],
  adiós: ["Adiós, hasta luego.", "Te digo adiós porque me voy."],
  "por favor": ["Por favor, abre la puerta.", "Dame agua, por favor."],
  gracias: ["Gracias por tu ayuda.", "Gracias, no te preocupes."],
  perdón: ["Perdón, llegué tarde.", "¿Me perdonas?"],
  sí: ["Sí, quiero estudiar.", "Sí, lo hago ahora."],
  no: ["No, no puedo ir hoy.", "No, gracias."],
  bien: ["Estoy bien, gracias.", "Hoy me siento bien."],
  mal: ["Hoy me siento mal.", "No me fue bien, me sentí mal."],
  hoy: ["Hoy es lunes.", "Hoy estoy en casa."],
  mañana: ["Mañana voy a trabajar.", "La clase es mañana."],
  ayer: ["Ayer vi una película.", "Ayer llovió toda la tarde."],
  ahora: ["Ahora es un buen momento.", "Ahora hablamos en clase."],
  siempre: ["Siempre estudio por la noche.", "Ella siempre sonríe."],
  nunca: ["Nunca digo mentiras.", "Nunca desayuno tarde."],
  yo: ["Yo soy estudiante.", "Yo hablo español."],
  tú: ["Tú eres mi amigo.", "Tú tienes un libro."],
  usted: ["¿Usted quiere café?", "¿Cómo está usted?"],
  él: ["Él vive en Madrid.", "Él es mi profesor."],
  ella: ["Ella es médica.", "Ella viene mañana."],
  nosotros: ["Nosotros hablamos español.", "Nosotros vamos a casa."],
  nosotras: ["Nosotras estudiamos juntas.", "Nosotras somos amigas."],
  ellos: ["Ellos trabajan hoy.", "Ellos van a la tienda."],
  ellas: ["Ellas comen fruta.", "Ellas viven aquí."],
  qué: ["¿Qué quieres?", "¿Qué hora es?"],
  quién: ["¿Quién eres?", "¿Quién viene con nosotros?"],
  dónde: ["¿Dónde estás?", "¿Dónde vives?"],
  cuándo: ["¿Cuándo vienes?", "¿Cuándo es la clase?"],
  cómo: ["¿Cómo estás?", "¿Cómo se dice?"],
  cuánto: ["¿Cuánto cuesta esto?", "¿Cuánto tiempo necesitas?"],
  uno: ["Tengo uno de estos libros.", "Es uno de mis amigos."],
  dos: ["Dos personas vienen hoy.", "Compré dos cafés."],
  tres: ["Tengo tres perros.", "Tres días de vacaciones."],
  cuatro: ["Cuatro amigos vinieron.", "Hay cuatro sillas."],
  cinco: ["Cinco minutos, por favor.", "Compré cinco panes."],
  seis: ["La clase dura seis horas.", "Tenemos seis días."],
  siete: ["Siete niños jugaron.", "Siete años de experiencia."],
  ocho: ["Ocho personas en mi clase.", "A las ocho llego."],
  nueve: ["Nueve libros en la mochila.", "Nueve estudiantes presentes."],
  diez: ["Diez minutos para empezar.", "Hay diez meses al año."],
  cero: ["Cero errores hoy.", "La nota fue un cero."],
  persona: ["Esa persona es alta.", "La persona vive aquí."],
  hombre: ["El hombre trabaja aquí.", "El hombre de la foto."],
  mujer: ["La mujer es profesora.", "Una mujer amable."],
  niño: ["El niño está feliz.", "Un niño corría."],
  niña: ["La niña estudia mucho.", "Una niña con libros."],
  amigo: ["Mi amigo vive conmigo.", "Ese amigo es simpático."],
  amiga: ["Mi amiga habla inglés.", "La amiga de Ana."],
  familia: ["Mi familia es grande.", "Tengo una familia pequeña."],
  madre: ["Mi madre cocina bien.", "Mi madre trabaja hoy."],
  padre: ["Mi padre llega temprano.", "El padre de Ana es amable."],
  hermano: ["Mi hermano es alto.", "Mi hermano juega fútbol."],
  hermana: ["Mi hermana estudia mucho.", "La hermana de María."],
  profesor: ["El profesor llega pronto.", "El profesor enseña español."],
  profesora: ["La profesora ayuda mucho.", "La profesora es muy amable."],
  estudiante: ["Soy estudiante de español.", "Ella es estudiante."],
  casa: ["Estoy en casa.", "La casa es grande."],
  escuela: ["La escuela está cerca.", "Voy a la escuela cada día."],
  clase: ["La clase comienza a las nueve.", "Esta clase es fácil."],
  ciudad: ["La ciudad es grande.", "Vivimos en una gran ciudad."],
  país: ["Este país tiene muchas playas.", "Me gusta este país."],
  calle: ["La calle está llena.", "Vivo en la calle principal."],
  tienda: ["Voy a la tienda.", "La tienda está abierta."],
  trabajo: ["Trabajo en una oficina.", "Estoy en el trabajo."],
  restaurante: ["Cenamos en un restaurante.", "Ese restaurante es caro."],
  baño: ["El baño está ocupado.", "Voy al baño."],
  agua: ["Quiero agua, por favor.", "El agua está fría."],
  café: ["Tomo café en la mañana.", "¿Quieres café?"],
  té: ["Tomo té por la tarde.", "El té es caliente."],
  leche: ["La leche está en la nevera.", "Quiero leche en mi café."],
  pan: ["El pan está fresco.", "Quiero pan con mantequilla."],
  arroz: ["Comemos arroz con pollo.", "Arroz para la comida."],
  pollo: ["Me gusta el pollo.", "Ceno pollo hoy."],
  pescado: ["El pescado está caro.", "Comí pescado esta noche."],
  carne: ["La carne está deliciosa.", "La carne viene con salsa."],
  fruta: ["Como fruta cada día.", "La fruta está madura."],
  manzana: ["Me gusta la manzana.", "La manzana es dulce."],
  verdura: ["La verdura es saludable.", "Cocina verdura fresca."],
  mesa: ["La mesa está limpia.", "Pon la mochila en la mesa."],
  silla: ["La silla es de madera.", "Siéntate en la silla."],
  libro: ["Este libro es mío.", "Leí el libro."],
  cuaderno: ["Mi cuaderno es azul.", "Escribe en el cuaderno."],
  teléfono: ["Llamé por teléfono.", "Mi teléfono está roto."],
  computadora: ["La computadora funciona.", "Compré una nueva computadora."],
  dinero: ["Necesito dinero hoy.", "No tengo dinero."],
  coche: ["Subo al coche.", "Mi coche es rojo."],
  tren: ["Voy en tren.", "El tren llega temprano."],
  autobús: ["El autobús pasa a las ocho.", "Subo al autobús."],
  ser: ["Soy profesor.", "Soy español."],
  estar: ["Estoy aquí.", "Estamos listos."],
  tener: ["Tengo una pregunta.", "¿Tienes tiempo?"],
  hacer: ["Hago mi tarea.", "¿Qué quieres hacer?"],
  ir: ["Voy a casa.", "Vamos a trabajar."],
  venir: ["Vengo mañana.", "¿Vienes hoy?"],
  vivir: ["Vivo en Madrid.", "Vivimos juntos."],
  hablar: ["Hablo con mi amiga.", "Hablamos después."],
  comer: ["Como pan.", "Vamos a comer."],
  beber: ["Bebo té en la noche.", "Vamos a beber agua."],
  leer: ["Leo un libro.", "Lea antes de clase."],
  escribir: ["Escribo una carta.", "Escribe tu nombre."],
  comprar: ["Compro pan hoy.", "Compramos en la tienda."],
  ver: ["Veo una película.", "¿Quieres ver eso?"],
  escuchar: ["Escucho música.", "Te escucho ahora."],
  querer: ["Quiero aprender.", "Quiero dormir."],
  grande: ["La casa es grande.", "Un gato grande."],
  pequeño: ["El cuarto es pequeño.", "Un perro pequeño."],
  bueno: ["Esto está bueno.", "Él es bueno en eso."],
  malo: ["Esto se sabe mal.", "Me siento mal."],
  nuevo: ["Compré algo nuevo.", "Es un coche nuevo."],
  viejo: ["La casa vieja.", "Ese coche es viejo."],
  bonito: ["Qué lugar bonito.", "Te veo en un lugar bonito."],
  fácil: ["El problema es fácil.", "Esto es fácil."],
  difícil: ["Este ejercicio es difícil.", "Es difícil, pero puedo practicar."],
  caliente: ["El té está caliente.", "Está muy caliente."],
  frío: ["Hace frío hoy.", "El agua está fría."],
  rápido: ["Vamos rápido.", "Habla más rápido."],
  lento: ["Ve despacio, no rápido.", "El reloj va lento."],
  mucho: ["Tengo mucho trabajo.", "Me gusta mucho."],
  poco: ["Tengo poco tiempo.", "Quiero poco azúcar."],
  aquí: ["Estoy aquí.", "Quédate aquí."],
  allí: ["Estoy allí.", "Allí vive Ana."],
  con: ["Voy con mi hermana.", "Café con leche."],
  sin: ["Sin problema.", "Café sin azúcar."],
  en: ["Estoy en casa.", "Libro en la mesa."],
  de: ["Taza de té.", "Soy de Madrid."],
  para: ["Esto es para ti.", "Ven para acá."],
  porque: ["No vengo porque llueve.", "Gracias porque ayudaste."],
};
